java8: true
swaggerDocketConfig: true
hideGenerationTimestamp: true

artifactId: algosim-compiler-server
artifactVersion: 0.0.1
groupId: hse.algosim.compiler

basePackage: hse.algosim.compiler.server
apiPackage: hse.algosim.compiler.server.api
invokerPackage: hse.algosim.compiler.server.api
modelPackage: hse.algosim.compiler.server.model
configPackage: hse.algosim.compiler.server.config
