version: '3.7'

services:
   repo:
     image: repo-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
   compiler:
     image: compiler-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
     volumes:
       - ~/.m2:/root/.m2
   executor:
     image: executor-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
   gateway:
     image: gateway-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
     ports:
       - 8080:8080
