# we wont work with clients a lot, so I just build all of them together and use in other stages
# it will be cached and wont be built every time the build starts
FROM maven:3.6.2-jdk-8 AS clients-builder
COPY ./compiler/client /app/compiler
COPY ./executor/client /app/executor
COPY ./repo/client /app/repo
RUN cd /app/repo && mvn clean install && \
    cd /app/compiler && mvn clean install && \
    cd /app/executor && mvn clean install
