version: '3.7'

services:
   repo:
     image: repo-server
     command: --server.port=8080
   compiler:
     image: compiler-server
     command: --server.port=8080
     volumes:
       - ~/.m2:/root/.m2
   executor:
     image: executor-server
     command: --server.port=8080
     volumes:
       - ./quotes:/quotes
   gateway:
     image: gateway-server
     command: --server.port=8080
     ports:
       - 8080:8080
