version: '3.7'

services:
   repo:
     image: repo-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--spring.datasource.driverClassName=org.postgresql.Driver"
       - "--spring.datasource.url=jdbc:postgresql://database:5432/algosim"
       - "--spring.datasource.username=postgres"
       - "--spring.datasource.password=postgres"
     environment:
       - API_CLIENT_USER=admin
       - API_CLIENT_PASSWORD=admin
     healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
       interval: 30s
       timeout: 10s
       retries: 5
   compiler:
     image: compiler-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--framework.project.path=/framework"
       - "--repo.basePath=http://repo:8080/api"
       - "--spring.datasource.driverClassName=org.postgresql.Driver"
       - "--spring.datasource.url=jdbc:postgresql://database:5432/algosim"
       - "--spring.datasource.username=postgres"
       - "--spring.datasource.password=postgres"
     environment:
       - API_CLIENT_USER=admin
       - API_CLIENT_PASSWORD=admin
     volumes:
       - ~/.m2:/root/.m2
   executor:
     image: executor-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--framework.quotes.path=/quotes"
       - "--repo.basePath=http://repo:8080/api"
       - "--gateway.basePath=http://gateway:8080"
       - "--spring.datasource.driverClassName=org.postgresql.Driver"
       - "--spring.datasource.url=jdbc:postgresql://database:5432/algosim"
       - "--spring.datasource.username=postgres"
       - "--spring.datasource.password=postgres"
     environment:
       - API_CLIENT_USER=admin
       - API_CLIENT_PASSWORD=admin
   gateway:
     image: gateway-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--repo.basePath=http://repo:8080/api"
       - "--compiler.basePath=http://compiler:8080/api"
       - "--executor.basePath=http://executor:8080/api"
       - "--spring.datasource.driverClassName=org.postgresql.Driver"
       - "--spring.datasource.url=jdbc:postgresql://database:5432/algosim"
       - "--spring.datasource.username=postgres"
       - "--spring.datasource.password=postgres"
     ports:
       - 8080:8080
     environment:
       - API_CLIENT_USER=admin
       - API_CLIENT_PASSWORD=admin
   database:
     image: postgres:12-alpine
     ports:
       - 5432:5432
     environment:
       - POSTGRES_PASSWORD=postgres
     volumes:
       - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh


