version: '3.7'

services:
   repo:
     image: repo-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--platform.username=user"
       - "--platform.password=password"
   compiler:
     image: compiler-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--framework.project.path=/framework"
       - "--platform.username=user"
       - "--platform.password=password"
       - "--repo.basePath=http://repo:8080/api"
     volumes:
       - ~/.m2:/root/.m2
   executor:
     image: executor-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--framework.quotes.path=/quotes"
       - "--framework.database.user=postgres"
       - "--framework.database.password=postgres"
       - "--framework.database.hostport=database:5432"
       - "--framework.database.name=algosim"
       - "--platform.username=user"
       - "--platform.password=password"
       - "--repo.basePath=http://repo:8080/api"
   gateway:
     image: gateway-server
     command:
       - "--server.port=8080"
       - "--server.address=0.0.0.0"
       - "--platform.username=user"
       - "--platform.password=password"
       - "--repo.basePath=http://repo:8080/api"
       - "--compiler.basePath=http://compiler:8080/api"
       - "--executor.basePath=http://executor:8080/api"
     ports:
       - 8080:8080
   database:
     image: postgres:12-alpine
     ports:
       - 5432:5432
     environment:
       - POSTGRES_PASSWORD=postgres
     volumes:
       - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh


