openapi: "3.0.0"
info:
  version: 0.0.1
  title: Algosim gateway
  description: A gateway service for collab project of HSE and Deutsche Bank aiming to improve trading algorithms testing. Entrypoint of the whole thing. Here the scheduling logic resides.
  contact:
    name: developers
    email: kirkondrash@yandex.ru
servers:
  - url: http://localhost:8080/api
      
paths:
  /algoCode:
    post:
      description: Gets code loaded by user, assigns the id to it. The code will later be compiled and executed
      operationId: getAlgorithmCode
      requestBody:
        description: Source code to be uploaded
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SrcCode'
      responses:
        '201':
          description: Source code was uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SrcId'
security:
  - basicAuth: []  # <-- use the same name here

components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  schemas:
    SrcCode:
      type: object
      properties:
        code:
          type: string
          format: binary
    SrcId:
      type: string
