/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hse.algosim.repo.server.api;

import org.springframework.core.io.Resource;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "algoJar", description = "the algoJar API")
public interface AlgoJarApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "", nickname = "deleteAlgorithmJar", notes = "deletes the algorithm jar based on the UUID supplied", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Artifact successfully deleted"),
        @ApiResponse(code = 404, message = "Artifact not found for this UUID") })
    @RequestMapping(value = "/algoJar/{id}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteAlgorithmJar(@ApiParam(value = "UUID of algorithm to delete",required=true) @PathVariable("id") UUID id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "", nickname = "findAlgorithmJar", notes = "Returns algorithm jar", response = Resource.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "source code and description", response = Resource.class),
        @ApiResponse(code = 404, message = "Artifact not found for this UUID") })
    @RequestMapping(value = "/algoJar/{id}",
        produces = { "application/octet-stream" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Resource> findAlgorithmJar(@ApiParam(value = "UUID of algorithm to fetch",required=true) @PathVariable("id") UUID id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "", nickname = "uploadAlgorithmJar", notes = "Uploads algorithm artifact", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully uploaded to nexus"),
        @ApiResponse(code = 404, message = "Source code not found for this UUID") })
    @RequestMapping(value = "/algoJar/{id}",
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> uploadAlgorithmJar(@ApiParam(value = "UUID of algorithm which jar is uploaded",required=true) @PathVariable("id") UUID id,@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile jar) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
