/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hse.algosim.repo.server.api;

import hse.algosim.repo.server.model.SrcMeta;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "algoMeta", description = "the algoMeta API")
public interface AlgoMetaApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "", nickname = "deleteAlgorithmMeta", notes = "Clears algorithm metadata", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Metadata successfully cleared"),
        @ApiResponse(code = 404, message = "Metadata not found for this UUID") })
    @RequestMapping(value = "/algoMeta/{id}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteAlgorithmMeta(@ApiParam(value = "UUID of algorithm which metadata will be cleared",required=true) @PathVariable("id") UUID id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "", nickname = "findAlgorithmMeta", notes = "Returns algorithm metadata", response = SrcMeta.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Metadata", response = SrcMeta.class),
        @ApiResponse(code = 404, message = "Metadata not found for this UUID") })
    @RequestMapping(value = "/algoMeta/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<SrcMeta> findAlgorithmMeta(@ApiParam(value = "UUID of algorithm which metadata is fetched",required=true) @PathVariable("id") UUID id) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"author\" : \"John Doe\",  \"description\" : \"Based on Stealth\"}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "", nickname = "uploadAlgorithmMeta", notes = "Loads algorithm metadata like description or author", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The metadata was uploaded successfully"),
        @ApiResponse(code = 404, message = "Source not found for this UUID") })
    @RequestMapping(value = "/algoMeta/{id}",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> uploadAlgorithmMeta(@ApiParam(value = "UUID of algorithm which metadata is uploaded",required=true) @PathVariable("id") UUID id,@ApiParam(value = "Metadata to be uploaded" ,required=true )  @Valid @RequestBody SrcMeta srcMeta) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
