/*
 * Algosim compiler
 * A compiler service for collab project of HSE and Deutsche Bank aiming to improve trading algorithms testing. Gets the source code from the repo and compiles it.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: kirkondrash@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package hse.algosim.compiler.client.api;

import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class CompilerApiClientInstanceTest {

    private final CompilerApiClientInstance api = new CompilerApiClientInstance();

    
    /**
     * 
     *
     * Gets the sources from the db and compiles them
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void compileAlgorithmTest() throws ApiException {
        UUID id = null;
        api.compileAlgorithm(id);

        // TODO: test validations
    }
    
}
