FROM algosim-base AS repo-builder
WORKDIR /app/server
COPY . /app/server
RUN mvn package

FROM algosim-dist-jre AS repo-dist
COPY --from=repo-builder /app/server/target/algosim-repo-server-0.0.1.jar  /app/app.jar
