/*
 * Algosim repo
 * A repo service for collab project of HSE and Deutsche Bank aiming to improve trading algorithms testing. Service linked to:   - the db for algorithm description, source code and benchmarks   - nexus for the artifacts    
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: kirkondrash@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package hse.algosim.repo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;

/**
 * SrcJar
 */

public class SrcJar {
  public static final String SERIALIZED_NAME_JAR = "jar";
  @SerializedName(SERIALIZED_NAME_JAR)
  private File jar;


  public SrcJar jar(File jar) {
    
    this.jar = jar;
    return this;
  }

   /**
   * Get jar
   * @return jar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public File getJar() {
    return jar;
  }


  public void setJar(File jar) {
    this.jar = jar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SrcJar srcJar = (SrcJar) o;
    return Objects.equals(this.jar, srcJar.jar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SrcJar {\n");
    sb.append("    jar: ").append(toIndentedString(jar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

