FROM algosim-base AS compiler-builder
WORKDIR /app
COPY . /app
RUN mvn package

FROM algosim-dist-jdk AS compiler-dist
COPY --from=compiler-builder /framework  /framework
COPY --from=compiler-builder /app/target/compiler-server-0.0.1.jar  /app/app.jar
