FROM algosim-base AS executor-builder
WORKDIR /app
COPY . /app
RUN mvn package

FROM algosim-dist-jre AS executor-dist
COPY --from=executor-builder /app/target/executor-server-0.0.1.jar  /app/app.jar
