FROM algosim-base AS executor-builder
WORKDIR /app/server
COPY . /app/server
RUN mvn package

FROM algosim-dist AS executor-dist
COPY --from=executor-builder /app/server/target/algosim-executor-server-0.0.1.jar  /app/app.jar
