openapi: "3.0.0"
info:
  version: 0.0.1
  title: Algosim-executor
  description: A collab project of HSE and Deutsche Bank aiming to improve trading algorithms testing. Gets the artifact from nexus and executes it.
  contact:
    name: developers
    email: kirkondrash@yandex.ru
servers:
  - url: http://localhost:8080/api
      
paths:
  /execute/{id}:
    post:
      tags:
        - executor
      description: Gets the artifact from nexus, executes and benchmarks it
      operationId: executeAlgorithm
      parameters:
        - name: id
          in: path
          description: id of algorithm to fetch
          required: true
          schema:
            $ref: '#/components/schemas/SrcId'
      responses:
        '200':
          description: Successfully executed
        '404':
          description: Artifact not found for this id
  /ready:
    get:
      tags:
        - executor
      description: Returns readiness of the host for execution
      operationId: getReadiness
      responses:
        '200':
          description: Ready
        '503':
          description: Busy
security:
  - basicAuth: []

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SrcId:
      type: string