/*
 * Algosim-executor
 * A collab project of HSE and Deutsche Bank aiming to improve trading algorithms testing. Gets the artifact from nexus and executes it.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: kirkondrash@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package hse.algosim.executor.client.api;

import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class ExecutorApiClientInstanceTest {

    private final ExecutorApiClientInstance api = new ExecutorApiClientInstance();

    
    /**
     * 
     *
     * Gets the artifact from nexus, executes and benchmarks it
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeAlgorithmTest() throws ApiException {
        UUID id = null;
        api.executeAlgorithm(id);

        // TODO: test validations
    }
    
}
